apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: humor-game
spec:
  ports:
    - port: 3001
  selector:
    app: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: humor-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:local
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: "postgres://humor:humorpass@postgres:5432/humor"
            - name: REDIS_URL
              value: "redis://redis:6379"
